MOMENTO 1:COMPRENSION DEL PROBLEMA Y RECONOCIMIENTO DE LOS DATOS

3. Identifique los cinco archivos suministrados y explique qué información considera que
almacena cada uno.

instacart_orders.csv:Los pedidos hechos en la app

productos.csv:El catalogo de productos

order_products.csv:El detalle de cada pedido

aisles.csv:Los nombres de los pasillos.

departments.csv:Los nombres de los departamentos

4. Reconozca qué columnas podrían utilizarse para identificar pedidos, usuarios y productos.

Para identificar pedidos: order_id. Aparece en instacart_orders (una fila por pedido) y en order_products (una fila por articulo del pedido).

Para identificar usuarios: user_id. Aparece en instacart_orders y permite identificar la cuenta de cada cliente.

Para identificar productos: product_id. Aparece en products (una fila por producto) y en order_products

5. Formule tres preguntas de análisis relacionadas con los hábitos de compra que puedan
responderse mediante las operaciones básicas estudiadas.

1. ¿En que dia de la semana y a que hora se hacen mas pedidos?

2. ¿Cuanto tiempo suelen esperar los clientes entre un pedido y el siguiente?

3. ¿Cuales son los productos que mas se piden y cuales se recompran con mas frecuencia?

Registre en su Notebook la descripción del problema, las preguntas y una explicación sobre la
importancia de explorar los datos antes de analizarlos.

- Descripcion del problema :

Instacart es una plataforma de entrega de viveres a domicilio y  a mi como analista de datos me piden explorar los pedidos para entender como compran los clientes.

- Importancia de explorar los datos antes de analizarlos:

Antes de empezar a analizar datos es de suma importancia conocer los datos y el problema para conocer el objetivo de el analisis.

MOMENTO 2 :IMPORTACION Y EXPLORACION INICIAL DE LOS ARCHIVOS

In [5]:
import sys
import pandas as pd

print(sys.version_info.major, sys.version_info.minor)
print(pd.__version__)

3 13
3.1.0

In [2]:
import pandas as pd

orders = pd.read_csv("../data/instacart_orders.csv", sep=";")
products = pd.read_csv("../data/products.csv", sep=";")
aisles = pd.read_csv("../data/aisles.csv", sep=";")
departments = pd.read_csv("../data/departments.csv", sep=";")
order_products = pd.read_csv("../data/order_products.csv", sep=";")

6. Utilice head() y tail() para observar los primeros y últimos cinco registros de cada DataFrame.

In [4]:
print("orders - primeros 5")
display(orders.head())
print("orders - últimos 5")
display(orders.tail())

orders - primeros 5

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,1515936,183418,11,6,13,30.0
1,1690866,163593,5,5,12,9.0
2,1454967,39980,4,5,19,2.0
3,1768857,82516,56,0,20,10.0
4,3007858,196724,2,4,12,17.0

orders - últimos 5

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
478962,3210681,5617,5,1,14,7.0
478963,3270802,112087,2,3,13,6.0
478964,885349,82944,16,2,11,6.0
478965,216274,4391,3,3,8,8.0
478966,2071924,1730,18,1,14,15.0

7. Utilice shape para identificar la cantidad de filas y columnas.

In [7]:
dataframes = {
    "orders": orders,
    "products": products,
    "aisles": aisles,
    "departments": departments,
    "order_products": order_products,
}

In [8]:
for nombre, df in dataframes.items():
    print(f"{nombre}: {df.shape[0]} filas y {df.shape[1]} columnas")

orders: 478967 filas y 6 columnas
products: 49694 filas y 4 columnas
aisles: 134 filas y 2 columnas
departments: 21 filas y 2 columnas
order_products: 4545007 filas y 4 columnas

¿Cuál de los cinco DataFrames contiene más registros?

El DataFrame con mayor cantidad de registros es  order_products, con 4,545,007 filas.

¿Cuál contiene menos columnas?

Los DataFrames con menos columnas son aisles y departments, con 2 columnas cada uno. Esto se debe a que son tablas de consulta: solo guardan un identificador (aisle_id o department_id) y el nombre correspondiente (aisle o department).

¿Qué diferencias identifica entre los datos de pedidos y los datos de productos?


La informacion de los pedidos(orders, con 478,967 filas y 6 columnas) describen el comportamiento de compra: quién hizo cada pedido, en qué día y hora, y cuánto tiempo pasó desde el anterior. Los datos de productos (products, con 49,694 filas y 4 columnas) describen el catálogo: el nombre de cada producto y el pasillo y departamento al que pertenece. Los pedidos son eventos que se repiten en el tiempo, mientras que los productos son un catálogo de referencia. Ambos se conectan a través de order_products, que indica qué productos hay en cada pedido.

¿Por qué es importante conocer las dimensiones de un conjunto de datos?

Las razones principales:

- Verificar la importacion : si una tabla sale con una sola columna ,fallo el ";" .

Si sale con muy pocas filas,el archivo pudo leerse incompleto

- Dimensionar el trabajo: No es lo mismo procesar 21 filas (departments) que 4,545,007 (order_products).

Con tablas grandes se gasta mas memoria.

- Planear el analisis : saber cuántas columnas hay indica qué variables puedes usar. Por ejemplo, orders tiene 6 columnas, suficientes para analizar día, hora y frecuencia de compra.

- Entender como se relacionan las tablas:las proporciones dan pistas. order_products tiene casi diez veces más filas que orders, lo que indica que cada pedido tiene en promedio varios artículos.

- Comprobar resultados despues : si al unir tablas con merge() el numero de filas cambia de forma inesperada,es señal de duplicados o de una unión mal hecha.

MOMENTO 3 : RECONOCIMIENTO DE LA ESTRUCTURA Y CALIDAD INICIAL DE LOS DATOS

- Identifique los nombres de las columnas de cada archivo.

In [11]:
for nombre, df in dataframes.items():
    print(f"{nombre}: {list(df.columns)}")

orders: ['order_id', 'user_id', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order']
products: ['product_id', 'product_name', 'aisle_id', 'department_id']
aisles: ['aisle_id', 'aisle']
departments: ['department_id', 'department']
order_products: ['order_id', 'product_id', 'add_to_cart_order', 'reordered']

- Determine qué columnas contienen valores enteros, decimales o texto.

In [12]:
for nombre, df in dataframes.items():
    print(f"===== {nombre} =====")
    print("Enteros:  ", list(df.select_dtypes(include="int").columns))
    print("Decimales:", list(df.select_dtypes(include="float").columns))
    print("Texto:    ", list(df.select_dtypes(include="object").columns))
    print()

===== orders =====
Enteros:   ['order_id', 'user_id', 'order_number', 'order_dow', 'order_hour_of_day']
Decimales: ['days_since_prior_order']
Texto:     []

===== products =====
Enteros:   ['product_id', 'aisle_id', 'department_id']
Decimales: []
Texto:     ['product_name']

===== aisles =====
Enteros:   ['aisle_id']
Decimales: []
Texto:     ['aisle']

===== departments =====
Enteros:   ['department_id']
Decimales: []
Texto:     ['department']

===== order_products =====
Enteros:   ['order_id', 'product_id', 'reordered']
Decimales: ['add_to_cart_order']
Texto:     []

C:\Users\Juan David Salazar T\AppData\Local\Temp\ipykernel_17000\3684118483.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/dev/user_guide/migration.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print("Texto:    ", list(df.select_dtypes(include="object").columns))
C:\Users\Juan David Salazar T\AppData\Local\Temp\ipykernel_17000\3684118483.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/dev/user_guide/migration.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print("Texto:    ", list(df.select_dtypes(include="object").columns))
C:\Users\Juan David Salazar T\AppData\Local\Temp\ipykernel_17000\3684118483.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/dev/user_guide/migration.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print("Texto:    ", list(df.select_dtypes(include="object").columns))

- Identifique cuáles son los campos que permiten relacionar conceptualmente los diferentes
conjuntos de datos.

In [13]:
from itertools import combinations

for (nombre1, df1), (nombre2, df2) in combinations(dataframes.items(), 2):
    comunes = set(df1.columns) & set(df2.columns)
    if comunes:
        print(f"{nombre1} ↔ {nombre2}: {sorted(comunes)}")

orders ↔ order_products: ['order_id']
products ↔ aisles: ['aisle_id']
products ↔ departments: ['department_id']
products ↔ order_products: ['product_id']

- Examine el número de valores no nulos reportado por info().

In [14]:
for nombre, df in dataframes.items():
    print(f"===== {nombre} =====")
    df.info()
    print()

===== orders =====
<class 'pandas.DataFrame'>
RangeIndex: 478967 entries, 0 to 478966
Data columns (total 6 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_id                478967 non-null  int64
 1   user_id                 478967 non-null  int64
 2   order_number            478967 non-null  int64
 3   order_dow               478967 non-null  int64
 4   order_hour_of_day       478967 non-null  int64
 5   days_since_prior_order  450148 non-null  float64
dtypes: float64(1), int64(5)
memory usage: 21.9 MB

===== products =====
<class 'pandas.DataFrame'>
RangeIndex: 49694 entries, 0 to 49693
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49694 non-null  int64
 1   product_name   48436 non-null  str
 2   aisle_id       49694 non-null  int64
 3   department_id  49694 non-null  int64
dtypes: int64(3), str(1)
memory usage: 1.5 MB

===== aisles =====
<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   aisle_id  134 non-null    int64
 1   aisle     134 non-null    str
dtypes: int64(1), str(1)
memory usage: 2.2 KB

===== departments =====
<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     str
dtypes: int64(1), str(1)
memory usage: 468.0 bytes

===== order_products =====
<class 'pandas.DataFrame'>
RangeIndex: 4545007 entries, 0 to 4545006
Data columns (total 4 columns):
 #   Column             Dtype
---  ------             -----
 0   order_id           int64
 1   product_id         int64
 2   add_to_cart_order  float64
 3   reordered          int64
dtypes: float64(1), int64(3)
memory usage: 138.7 MB

- Compare el número de registros con la cantidad de valores no nulos para reconocer posibles
datos ausentes.

In [15]:
for nombre, df in dataframes.items():
    print(f"===== {nombre} =====")
    comparacion = pd.DataFrame({
        "registros": len(df),
        "no_nulos": df.count(),
    })
    comparacion["ausentes"] = comparacion["registros"] - comparacion["no_nulos"]
    comparacion["% ausentes"] = (comparacion["ausentes"] / comparacion["registros"] * 100).round(2)
    display(comparacion)

===== orders =====

                        registros  no_nulos  ausentes  % ausentes
order_id                   478967    478967         0        0.00
user_id                    478967    478967         0        0.00
order_number               478967    478967         0        0.00
order_dow                  478967    478967         0        0.00
order_hour_of_day          478967    478967         0        0.00
days_since_prior_order     478967    450148     28819        6.02

===== products =====

               registros  no_nulos  ausentes  % ausentes
product_id         49694     49694         0        0.00
product_name       49694     48436      1258        2.53
aisle_id           49694     49694         0        0.00
department_id      49694     49694         0        0.00

===== aisles =====

          registros  no_nulos  ausentes  % ausentes
aisle_id        134       134         0         0.0
aisle           134       134         0         0.0

===== departments =====

               registros  no_nulos  ausentes  % ausentes
department_id         21        21         0         0.0
department            21        21         0         0.0

===== order_products =====

                   registros  no_nulos  ausentes  % ausentes
order_id             4545007   4545007         0        0.00
product_id           4545007   4545007         0        0.00
add_to_cart_order    4545007   4544171       836        0.02
reordered            4545007   4545007         0        0.00

- Elabore una tabla de diagnóstico con el nombre del archivo, cantidad de filas, cantidad de
columnas y observaciones sobre los datos.

In [16]:
filas_tabla = []

for nombre, df in dataframes.items():
    ausentes = df.isna().sum()
    ausentes = ausentes[ausentes > 0]
    duplicados = df.duplicated().sum()

    observaciones = []
    if ausentes.empty:
        observaciones.append("Sin datos ausentes")
    else:
        detalle = ", ".join(f"{col} ({n})" for col, n in ausentes.items())
        observaciones.append(f"Datos ausentes en: {detalle}")
    observaciones.append(f"{duplicados} filas duplicadas")

    filas_tabla.append({
        "Archivo": f"{nombre}.csv" if nombre != "orders" else "instacart_orders.csv",
        "Filas": df.shape[0],
        "Columnas": df.shape[1],
        "Observaciones": "; ".join(observaciones),
    })

diagnostico = pd.DataFrame(filas_tabla)
diagnostico

,Archivo,Filas,Columnas,Observaciones
0,instacart_orders.csv,478967,6,Datos ausentes en: days_since_prior_order (288...
1,products.csv,49694,4,Datos ausentes en: product_name (1258); 0 fila...
2,aisles.csv,134,2,Sin datos ausentes; 0 filas duplicadas
3,departments.csv,21,2,Sin datos ausentes; 0 filas duplicadas
4,order_products.csv,4545007,4,Datos ausentes en: add_to_cart_order (836); 0 ...

PREGUNTAS DE ANALISIS:

¿Qué diferencias existen entre int64, float64 y object?


int64 almacena números enteros, float64 números con decimales (y también columnas numéricas con valores ausentes) y object almacena texto.

¿Qué información proporciona info() que no se obtiene directamente con shape?

shape solo indica el número de filas y columnas. info() además muestra el nombre y el tipo de dato de cada columna y la cantidad de valores no nulos, lo que permite detectar datos ausentes.

¿En qué columnas se observan valores ausentes?

- days_since_prior_order (en orders): 28,819 valores ausentes de 478,967 registros (aprox. 6.02 %).
- product_name (en products): 1,258 valores ausentes de 49,694 registros (aprox. 2.53 %).
- add_to_cart_order (en order_products): 836 valores ausentes de 4,545,007 registros (aprox. 0.02 %).
Los DataFrames aisles y departments no presentan datos ausentes.

¿Qué posibles dificultades podrían generar estos valores en un análisis posterior?


Los valores ausentes pueden sesgar promedios y estadísticas, por ejemplo el promedio de días entre pedidos, que solo se calcularía con los pedidos que sí tienen dato. También pueden producir conteos incompletos, como productos sin nombre en un ranking de productos más pedidos, y cambiar el tipo de dato de una columna. Si no se revisan antes de analizar, pueden llevar a conclusiones erróneas.

MOMENTO 4: INDEXACION Y FILTRADO LOGICO

1. EJERCICIO

In [18]:
ej1 = products[["product_id", "product_name"]]
ej1.head()

   product_id                                       product_name
0           1                         Chocolate Sandwich Cookies
1           2                                   All-Seasons Salt
2           3               Robust Golden Unsweetened Oolong Tea
3           4  Smart Ones Classic Favorites Mini Rigatoni Wit...
4           5                          Green Chile Anytime Sauce

2. EJERCICIO

In [19]:
ej2 = products[products["department_id"] == 1]
print(len(ej2))
ej2.head()

4008

,product_id,product_name,aisle_id,department_id
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
7,8,Cut Russet Potatoes Steam N' Mash,116,1
11,12,Chocolate Fudge Layer Cake,119,1
17,18,Pizza for One Suprema Frozen Pizza,79,1
29,30,Three Cheese Ziti- Marinara with Meatballs,38,1

3. EJERCICIO

In [20]:
ej3 = orders[orders["order_hour_of_day"] == 10]
print(len(ej3))
ej3.head()

40578

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
19,294269,107523,29,2,10,1.0
28,133707,182261,1,3,10,NaN
36,3378084,127629,21,1,10,20.0
49,2161799,87345,7,0,10,24.0
51,1739741,118405,48,2,10,3.0

4. EJERCICIO

In [21]:
ej4 = orders[orders["order_dow"] == 0]
print(len(ej4))
ej4.head()

84090

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
3,1768857,82516,56,0,20,10.0
5,1843871,20084,5,0,11,15.0
7,2521283,97711,2,0,18,22.0
23,3406282,19356,21,0,0,14.0
25,1895419,169793,2,0,11,8.0

5. EJERCICIO

In [22]:
ej5 = orders[orders["order_number"] > 10]
print(len(ej5))
ej5.head()

244072

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,1515936,183418,11,6,13,30.0
3,1768857,82516,56,0,20,10.0
6,2511640,148233,40,3,8,2.0
8,2266494,34954,40,5,15,4.0
10,1162566,43738,33,4,11,2.0

6. EJERCICIO

In [23]:
ej6 = orders[orders["days_since_prior_order"] > 15]
print(len(ej6))
ej6.head()

110706

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,1515936,183418,11,6,13,30.0
4,3007858,196724,2,4,12,17.0
7,2521283,97711,2,0,18,22.0
14,2843219,74699,4,6,11,30.0
26,1844247,122558,4,6,18,30.0

7. EJERCICIO

In [24]:
ej7 = order_products[order_products["reordered"] == 1]
print(len(ej7))
ej7.head()

2683838

   order_id  product_id  add_to_cart_order  reordered
1    567889        1560                1.0          1
2   2261212       26683                1.0          1
3    491251        8670               35.0          1
4   2571142        1940                5.0          1
5   2456893       21616                4.0          1

8.EJERCICIO

In [25]:
ej8 = order_products[order_products["add_to_cart_order"] == 1]
print(len(ej8))
ej8.head()

450046

    order_id  product_id  add_to_cart_order  reordered
1     567889        1560                1.0          1
2    2261212       26683                1.0          1
14   1961225       37553                1.0          1
16    639939       10017                1.0          1
23    750040        8518                1.0          0